# Generated by Django 4.2.3 on 2023-09-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_products_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='groundspace',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='rating',
            new_name='catagories',
        ),
    ]
