# Generated by Django 4.2.3 on 2023-09-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_rename_groundspace_products_brands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='email',
            new_name='color',
        ),
    ]
