# Generated by Django 4.2.3 on 2023-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_email_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='modelfile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
