# Generated by Django 4.2.3 on 2023-09-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_register_modelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='modelfile',
            new_name='image',
        ),
    ]
