# Generated by Django 4.2.3 on 2023-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
